/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-m2k
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_M2K_API_H
#define INCLUDED_M2K_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_m2k_EXPORTS
#define M2K_API __GR_ATTR_EXPORT
#else
#define M2K_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_M2K_API_H */
