/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(analog_out_converter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b1e7798d61c58651d9c9ae1467101658)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m2k/analog_out_converter.h>
// pydoc.h is automatically generated in the build directory
#include <analog_out_converter_pydoc.h>

void bind_analog_out_converter(py::module& m)
{

    using analog_out_converter    = ::gr::m2k::analog_out_converter;


    py::class_<analog_out_converter, gr::sync_block, gr::block, gr::basic_block,
        PYBIND11_SH_DEF(analog_out_converter)>(m, "analog_out_converter", D(analog_out_converter))

        .def(py::init(&analog_out_converter::make),
           py::arg("uri"),
           D(analog_out_converter,make)
        )
        




        
        .def_static("make_from",&analog_out_converter::make_from,       
            py::arg("context"),
            D(analog_out_converter,make_from)
        )

        ;




}








