/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(analog_in_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1d3d64fde4d37ae85e733a320f64ed8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m2k/analog_in_source.h>
// pydoc.h is automatically generated in the build directory
#include <analog_in_source_pydoc.h>

void bind_analog_in_source(py::module& m)
{

    using analog_in_source    = ::gr::m2k::analog_in_source;


    py::class_<analog_in_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<analog_in_source>>(m, "analog_in_source", D(analog_in_source))

        .def(py::init(&analog_in_source::make),
           py::arg("uri"),
           py::arg("buffer_size"),
           py::arg("channels"),
           py::arg("ranges"),
           py::arg("sampling_frequency"),
           py::arg("oversampling_ratio"),
           py::arg("kernel_buffers"),
           py::arg("calibrate_ADC"),
           py::arg("stream_voltage_values"),
           py::arg("trigger_condition"),
           py::arg("trigger_mode"),
           py::arg("trigger_source"),
           py::arg("trigger_delay"),
           py::arg("trigger_level"),
           py::arg("streaming"),
           py::arg("deinit") = true,
           py::arg("data_rate") = 0,
           D(analog_in_source,make)
        )
        




        
        .def_static("make_from",&analog_in_source::make_from,       
            py::arg("context"),
            py::arg("buffer_size"),
            py::arg("channels"),
            py::arg("ranges"),
            py::arg("sampling_frequency"),
            py::arg("oversampling_ratio"),
            py::arg("kernel_buffers"),
            py::arg("calibrate_ADC"),
            py::arg("stream_voltage_values"),
            py::arg("trigger_condition"),
            py::arg("trigger_mode"),
            py::arg("trigger_source"),
            py::arg("trigger_delay"),
            py::arg("trigger_level"),
            py::arg("streaming"),
            py::arg("deinit") = true,
            py::arg("data_rate") = 0,
            D(analog_in_source,make_from)
        )


        
        .def("set_params",&analog_in_source::set_params,       
            py::arg("ranges"),
            py::arg("sampling_frequency"),
            py::arg("oversampling_ratio"),
            D(analog_in_source,set_params)
        )


        
        .def("set_data_rate",&analog_in_source::set_data_rate,       
            py::arg("rate"),
            D(analog_in_source,set_data_rate)
        )


        
        .def("set_trigger",&analog_in_source::set_trigger,       
            py::arg("trigger_condition"),
            py::arg("trigger_mode"),
            py::arg("trigger_source"),
            py::arg("trigger_delay"),
            py::arg("trigger_level"),
            py::arg("streaming"),
            D(analog_in_source,set_trigger)
        )


        
        .def("set_timeout_ms",&analog_in_source::set_timeout_ms,       
            py::arg("timeout"),
            D(analog_in_source,set_timeout_ms)
        )


        
        .def("set_buffer_size",&analog_in_source::set_buffer_size,       
            py::arg("buffer_size"),
            D(analog_in_source,set_buffer_size)
        )

        ;




}








