/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(analog_out_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(47db38f995e62d65a81f7b7e548afde6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m2k/analog_out_sink.h>
// pydoc.h is automatically generated in the build directory
#include <analog_out_sink_pydoc.h>

void bind_analog_out_sink(py::module& m)
{

    using analog_out_sink    = ::gr::m2k::analog_out_sink;


    py::class_<analog_out_sink, gr::sync_block, gr::block, gr::basic_block,
        PYBIND11_SH_DEF(analog_out_sink)>(m, "analog_out_sink", D(analog_out_sink))

        .def(py::init(&analog_out_sink::make),
           py::arg("uri"),
           py::arg("buffer_size"),
           py::arg("sampling_frequency"),
           py::arg("oversampling_ratio"),
           py::arg("kernel_buffers"),
           py::arg("cyclic"),
           py::arg("calibrate_DAC"),
           py::arg("input_voltage"),
           D(analog_out_sink,make)
        )
        




        
        .def("set_params",&analog_out_sink::set_params,       
            py::arg("sampling_frequency"),
            py::arg("oversampling_ratio"),
            D(analog_out_sink,set_params)
        )

        ;




}








