/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(digital_in_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9bb870d58c3c6b4cb49107a50a76ced5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m2k/digital_in_source.h>
// pydoc.h is automatically generated in the build directory
#include <digital_in_source_pydoc.h>

void bind_digital_in_source(py::module& m)
{

    using digital_in_source    = ::gr::m2k::digital_in_source;


    py::class_<digital_in_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<digital_in_source>>(m, "digital_in_source", D(digital_in_source))

        .def(py::init(&digital_in_source::make),
           py::arg("uri"),
           py::arg("buffer_size"),
           py::arg("channel"),
           py::arg("sampling_frequency"),
           py::arg("kernel_buffers"),
           py::arg("streaming"),
           py::arg("deinit") = true,
           py::arg("data_rate") = 0,
           D(digital_in_source,make)
        )
        




        
        .def_static("make_from",&digital_in_source::make_from,       
            py::arg("context"),
            py::arg("buffer_size"),
            py::arg("channel"),
            py::arg("sampling_frequency"),
            py::arg("kernel_buffers"),
            py::arg("streaming"),
            py::arg("deinit") = true,
            py::arg("data_rate") = 0,
            D(digital_in_source,make_from)
        )


        
        .def("set_params",&digital_in_source::set_params,       
            py::arg("sampling_frequency"),
            py::arg("streaming"),
            D(digital_in_source,set_params)
        )


        
        .def("set_data_rate",&digital_in_source::set_data_rate,       
            py::arg("rate"),
            D(digital_in_source,set_data_rate)
        )


        
        .def("set_timeout_ms",&digital_in_source::set_timeout_ms,       
            py::arg("timeout"),
            D(digital_in_source,set_timeout_ms)
        )


        
        .def("set_buffer_size",&digital_in_source::set_buffer_size,       
            py::arg("buffer_size"),
            D(digital_in_source,set_buffer_size)
        )

        ;




}








