/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mixed_signal_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ee371dfef2d04758a573d834606c12a8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m2k/mixed_signal_source.h>
// pydoc.h is automatically generated in the build directory
#include <mixed_signal_source_pydoc.h>

void bind_mixed_signal_source(py::module& m)
{

    using mixed_signal_source    = ::gr::m2k::mixed_signal_source;


    py::class_<mixed_signal_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<mixed_signal_source>>(m, "mixed_signal_source", D(mixed_signal_source))

        .def(py::init(&mixed_signal_source::make),
           py::arg("context"),
           py::arg("buffer_size"),
           py::arg("data_rate") = 0,
           py::arg("kb") = 64,
           D(mixed_signal_source,make)
        )
        




        
        .def_static("make_from",&mixed_signal_source::make_from,       
            py::arg("context"),
            py::arg("buffer_size"),
            py::arg("data_rate") = 0,
            py::arg("kb") = 64,
            D(mixed_signal_source,make_from)
        )


        
        .def("set_timeout_ms",&mixed_signal_source::set_timeout_ms,       
            py::arg("timeout"),
            D(mixed_signal_source,set_timeout_ms)
        )


        
        .def("set_data_rate",&mixed_signal_source::set_data_rate,       
            py::arg("rate"),
            D(mixed_signal_source,set_data_rate)
        )


        
        .def("set_buffer_size",&mixed_signal_source::set_buffer_size,       
            py::arg("buffer_size"),
            D(mixed_signal_source,set_buffer_size)
        )

        ;




}








